-- Migration: Add Profitability Fields to Trips
-- Date: 2026-04-05
-- Description: Adds trip_revenue, trip_cost, trip_profit, trip_margin, customer_name, and route_name fields to the trips table

-- Add profitability columns to trips table
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_revenue DECIMAL(10,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_cost DECIMAL(10,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_profit DECIMAL(10,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_margin DECIMAL(5,4) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS route_name VARCHAR(255);

-- Add efficiency metric columns
ALTER TABLE trips ADD COLUMN IF NOT EXISTS mpg_score DECIMAL(5,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS deadhead_score DECIMAL(5,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS driver_cost_score DECIMAL(5,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS efficiency_score DECIMAL(5,2) DEFAULT 0;

-- Add risk metric columns
ALTER TABLE trips ADD COLUMN IF NOT EXISTS weather_risk DECIMAL(5,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS traffic_risk DECIMAL(5,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS breakdown_risk DECIMAL(5,2) DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS risk_score DECIMAL(5,2) DEFAULT 0;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_trips_customer_name ON trips(customer_name);
CREATE INDEX IF NOT EXISTS idx_trips_route_name ON trips(route_name);
CREATE INDEX IF NOT EXISTS idx_trips_margin ON trips(trip_margin);
CREATE INDEX IF NOT EXISTS idx_trips_profit ON trips(trip_profit);
CREATE INDEX IF NOT EXISTS idx_trips_efficiency ON trips(efficiency_score);
CREATE INDEX IF NOT EXISTS idx_trips_risk ON trips(risk_score);

-- Add comments for documentation
COMMENT ON COLUMN trips.trip_revenue IS 'Total revenue generated by the trip';
COMMENT ON COLUMN trips.trip_cost IS 'Total cost of operating the trip';
COMMENT ON COLUMN trips.trip_profit IS 'Net profit (revenue - cost)';
COMMENT ON COLUMN trips.trip_margin IS 'Profit margin (profit / revenue)';
COMMENT ON COLUMN trips.customer_name IS 'Customer or client name for grouping trips';
COMMENT ON COLUMN trips.route_name IS 'Route name for grouping and analysis';
COMMENT ON COLUMN trips.mpg_score IS 'Fuel efficiency score (0-100)';
COMMENT ON COLUMN trips.deadhead_score IS 'Deadhead miles efficiency score (0-100)';
COMMENT ON COLUMN trips.driver_cost_score IS 'Driver cost efficiency score (0-100)';
COMMENT ON COLUMN trips.efficiency_score IS 'Overall efficiency: (mpg_score + deadhead_score + driver_cost_score) / 3';
COMMENT ON COLUMN trips.weather_risk IS 'Weather-related risk score (0-100)';
COMMENT ON COLUMN trips.traffic_risk IS 'Traffic-related risk score (0-100)';
COMMENT ON COLUMN trips.breakdown_risk IS 'Vehicle breakdown risk score (0-100)';
COMMENT ON COLUMN trips.risk_score IS 'Overall risk: (weather_risk + traffic_risk + breakdown_risk) / 3';
